#!/usr/bin/env bash
# gen-brew-formula.sh — render the Homebrew FORMULA (Formula/roger.rb) for the tap.
#
# Why this exists (and isn't in .goreleaser.yaml): GoReleaser dropped Homebrew *formula*
# support in favour of casks (goreleaser.com/deprecations#brews). We want a formula, not a
# cask — a formula installs the same prebuilt per-arch binary, works on Linux Homebrew too
# (casks are macOS-only, and RogerAI providers run on Linux GPU boxes), and needs no
# `--cask` flag. So we template it ourselves from the release's checksums.txt — the SAME
# file web/install.sh trusts — which keeps the SHAs byte-for-byte in sync with the release.
#
# Usage:
#   scripts/gen-brew-formula.sh <version> [checksums.txt] [output.rb]
#
#   <version>       release version, with or without a leading v (5.2.1 or v5.2.1).
#   [checksums.txt] path to the release checksums; if omitted, it's downloaded from the
#                   v<version> GitHub release.
#   [output.rb]     where to write the formula; if omitted, it's printed to stdout.
#
# Examples:
#   scripts/gen-brew-formula.sh 5.2.1                       # fetch checksums, print formula
#   scripts/gen-brew-formula.sh 5.2.1 dist/checksums.txt Formula/roger.rb   # CI: from dist/
set -euo pipefail

OWNER_REPO="rogerai-fyi/roger"

die() { echo "gen-brew-formula: $*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: $0 <version> [checksums.txt] [output.rb]"
VERSION="${1#v}"                       # strip a leading v: v5.2.1 -> 5.2.1
CHECKSUMS="${2:-}"
OUT="${3:-}"

# Fetch checksums.txt from the release when not supplied (local convenience; CI passes dist/).
CLEANUP=""
if [ -z "$CHECKSUMS" ]; then
  CHECKSUMS="$(mktemp)"
  CLEANUP="$CHECKSUMS"
  URL="https://github.com/${OWNER_REPO}/releases/download/v${VERSION}/checksums.txt"
  curl -fsSL "$URL" -o "$CHECKSUMS" || die "could not download $URL"
fi
[ -f "$CHECKSUMS" ] || die "checksums file not found: $CHECKSUMS"
trap '[ -n "$CLEANUP" ] && rm -f "$CLEANUP"' EXIT

# Pull the sha256 for one release asset by its EXACT filename (checksums.txt is the standard
# `<sha256>  <name>` format). Fails loudly if the asset is missing or listed twice.
sha_for() {
  local name="$1" matches sha
  matches="$(grep -E "[[:space:]]${name}\$" "$CHECKSUMS" || true)"
  [ -n "$matches" ]                || die "no checksum for '$name' in $CHECKSUMS"
  [ "$(printf '%s\n' "$matches" | wc -l)" -eq 1 ] || die "'$name' listed more than once in $CHECKSUMS"
  sha="${matches%% *}"
  [ ${#sha} -eq 64 ]               || die "bad sha256 for '$name': '$sha'"
  printf '%s' "$sha"
}

DARWIN_ARM64="$(sha_for roger-darwin-arm64)"
DARWIN_AMD64="$(sha_for roger-darwin-amd64)"
LINUX_ARM64="$(sha_for roger-linux-arm64)"
LINUX_AMD64="$(sha_for roger-linux-amd64)"

# Heredoc the formula. `#{version}` is Ruby (Homebrew) interpolation, NOT shell — the URLs
# resolve to v<version>/roger-<os>-<arch> at install time. The prebuilt binary is staged as a
# single file (raw binary, not a tarball), so we install whatever landed as `roger`; a
# hardcoded name would be wrong because it differs per os/arch.
read -r -d '' FORMULA <<EOF || true
# This file is generated by scripts/gen-brew-formula.sh from the release checksums.txt.
# DO NOT EDIT — re-run the generator (or cut a new release) to update.
class Roger < Formula
  desc "Two-way radio for GPUs: consume and share LLM/voice models over the broker"
  homepage "https://rogerai.fyi"
  version "${VERSION}"
  # PolyForm Perimeter 1.0.0 — source-available, not an SPDX id, so \`brew audit\` can't
  # match it; :cannot_represent is Homebrew's blessed value for exactly this case.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/${OWNER_REPO}/releases/download/v#{version}/roger-darwin-arm64"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "https://github.com/${OWNER_REPO}/releases/download/v#{version}/roger-darwin-amd64"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${OWNER_REPO}/releases/download/v#{version}/roger-linux-arm64"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "https://github.com/${OWNER_REPO}/releases/download/v#{version}/roger-linux-amd64"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install Dir["*"].first => "roger"
  end

  test do
    assert_match "roger", shell_output("#{bin}/roger version 2>&1")
  end
end
EOF

if [ -n "$OUT" ]; then
  printf '%s\n' "$FORMULA" > "$OUT"
  echo "gen-brew-formula: wrote $OUT (v${VERSION})" >&2
else
  printf '%s\n' "$FORMULA"
fi
