# APPROVED SPEC - founder approved 2026-08-03. Changes to an approved scenario need
# re-approval; they are not a diff to be reviewed.
#
# Scope: exhaustive Cartesian tamper matrices for entitlement application descriptors, CanonicalTypedSetV1 and its registry rows, acyclic set construction graphs.
#
# One of five files split from the former single tamper_matrix.feature. The
# source-of-truth rule below applies to ALL FIVE collectively.
# The field lists below are the source of truth; summary field-mutation outlines in the
# subdomain specs do not reduce this matrix. Every new semantic field must be added here in
# the same spec change that introduces it.

Feature: Every signed Tower-network field rejects every universal post-signing mutation
  Strict decoding or role-specific signature verification rejects each independently
  applied field/operator pair before routing, trust, money, or compensation authority.

  Background:
    Given valid canonical objects with every field required by their selected origin and state
    And independent purpose-bound signing keys for every object role

  # Each object scenario executes the full Cartesian product of its field table and this
  # universal mutation set. This is not a sample: every pair is a separate test case.
  Scenario: Entitlement application descriptors have one closed mutation-exhaustive schema
    Given each descriptor in the entitlement_delta application set has these independently addressable fields:
      | field |
      | application kind |
      | application ID |
      | parent entitlement_delta stable ID |
      | plan-local half-open delta-atom-range start |
      | plan-local half-open delta-atom-range end |
      | causal positive source-event stable ID |
      | causal positive source-event half-open atom-range start |
      | causal positive source-event half-open atom-range end |
      | target object kind or canonical absence |
      | target object ID or canonical absence |
      | target object complete hash or canonical absence |
      | target half-open atom-range start or canonical absence |
      | target half-open atom-range end or canonical absence |
      | dependent target object kind or canonical absence |
      | dependent target object ID/complete hash or canonical absence |
      | dependent target half-open atom range or canonical absence |
      | payout-instruction complete hash or canonical absence |
      | PayoutSendFenceV1 complete hash or canonical absence |
      | exact share atoms |
      | currency |
      | unit |
      | scale |
      | expected prior state kind or canonical absence |
      | expected resulting state kind |
      | ApplicationResultRangeSetV1 complete hash |
    When each universal mutation is independently applied to each descriptor field or a descriptor is omitted, duplicated, reordered, or inserted while the entitlement_delta signature remains
    Then strict descriptor decoding or the ApplicationDescriptorSetV1 complete-hash relationship fails
    And for a positive delta the causal positive source event is the parent entitlement_delta with the same atom range, while for a negative delta it is the exact surviving prior-positive event/range selected by reverse recognition and proved by the target's immutable lineage
    And unknown application kinds, noncontiguous plan-local coverage, overlapping causal use in one lineage namespace, a range outside its immutable source/target, wrong parent/causal relation, wrong sign-to-kind mapping, or descriptor atoms not equal to each present range length rejects the whole reconciliation transaction
    And the only valid descriptor order is ascending plan-local delta-range start with the first start zero, every next start equal to the prior end, the final end equal to the absolute signed delta, and application ID UTF-8 bytes as a forbidden-to-need uniqueness check because two descriptors may not share a plan-local start
    And cross-lot, cross-debt, funding-slice, or application-kind boundaries split at the exact atom boundary into adjacent descriptors, so insertion order, target price, worker choice, or database collation cannot choose another encoding

  Scenario Outline: Application kind fixes target presence, kind, and state
    Given an application descriptor has kind "<application>"
    Then its only transaction-start target is "<target>"
    And its only prior-to-result relationship is "<states>"
    And every target ID/hash/range, dependent-target, instruction, or result field not named by that row has canonical absence

    Examples:
      | application | target | states |
      | lot_create | no target object or range | canonical prior absence to one exact immutable immature PayoutLotV1 result |
      | debt_offset | one outstanding DebtRangeV1 ID/hash/range | whole outstanding to recovered or parent partitioned plus one recovered selected child; one active DebtRecoveryApplicationV1 result |
      | debt_reopen | one active DebtRecoveryApplicationV1 ID/hash/source range and its dependent recovered DebtRangeV1 ID/hash/affine target range | whole active/recovered to reversed/outstanding or aligned partitioned selected-child results |
      | lot_cancel | one immature, mature_payable, or withheld unreserved PayoutLotV1 ID/hash/range | whole source state to cancelled or parent partitioned plus one cancelled selected child |
      | submitted_negative_fence | one reserved_submitted PayoutLotV1 ID/hash/range and its preexisting TowerPayoutInstructionV1/PayoutSendFenceV1 complete hashes | submitted lot remains reserved_submitted and one PendingSubmittedNegativeV1 is the realized result, never a target |
      | debt_create | one uncovered paid PayoutLotV1 ID/hash/range | paid remains paid and one economic_reversal DebtRangeV1 is the realized result |
      | enforcement_coverage_derecognize | one current EnforcementDispositionCoverageV1 ID/hash/range | current to derecognized or parent partitioned plus one derecognized selected child while the forensic lot remains unchanged |

  Scenario: CanonicalTypedSetV1 fixes every named compensation composite preimage
    Given a signed field names a set kind registered in the exact tables below
    When its complete hash is computed
    Then the preimage is exactly one strict JCS object containing schema version CanonicalTypedSetV1, network ID, protocol version, set-kind tag, owner-kind tag, stable owner ID, one strict kind-specific scope object, canonical member count, exact total share atoms or canonical not_applicable tag, and the complete member objects array
    And member count equals array length, each member has only its registered independently addressable fields, and members are sorted by the registered total key
    And sort component prefix u compares bounded canonical nonnegative decimal strings by mathematical unsigned value, b compares exact UTF-8 bytes, h compares decoded fixed-length hash bytes, and j compares exact UTF-8 JCS bytes; later components break ties and equality after the final component is a rejected duplicate
    And no locale, SQL collation, insertion order, floating conversion, signed integer conversion, or implementation tie-break participates
    And exact total atoms equals the registered conserving member total where applicable; the not_applicable tag is required otherwise, and count zero with the row-required canonical total tag—zero for a conserving set or not_applicable otherwise—and one empty members array is valid only for a row that explicitly permits empty
    And every registered half-open share-atom range has bounded canonical coordinates with zero less than or equal to start, start strictly less than end, and exact atoms equal to end minus start; an affine member requires that equality for both equal-length mapped ranges
    And nested sets appear only by their domain-separated complete hash in the registered acyclic direction; a set cannot contain its own or an ancestor set's object/hash
    And an unknown set kind/member field, missing scope field, null, alternate empty form, count/total mismatch, duplicate key/member, omitted/extra/reordered member, noncanonical integer, overflow, or wrong owner/scope fails before signature, state, posting, control, or rail authority

  Scenario Outline: Application and immutable child sets use exact registered members
    Given CanonicalTypedSetV1 kind "<set>" has owner kind "<owner>", owner ID copied from "<owner ID>", scope "<scope>", member fields "<members>", and total sort key "<key>"
    Then its conservation/cardinality contract is "<contract>"

    Examples:
      | set | owner | owner ID | scope | members | key | contract |
      | ApplicationDescriptorSetV1 | entitlement_delta | parent entitlement_delta stable ID | reconciliation transaction ID, aggregate ID/revision, signed delta, currency/unit/scale | complete strict entitlement application descriptor fields enumerated above | u:plan-local-start,u:plan-local-end,b:application-ID | count equals entitlement_delta descriptor count; ranges contiguously tile [0,absolute-D), total atoms equals absolute D, and only zero D permits empty |
      | ApplicationResultRangeSetV1 | application_descriptor | application ID | parent entitlement_delta ID, application kind, plan-local range, currency/unit/scale | closed result role, role segment index, state kind, EntityKeyV1, expected prior presence/state, expected resulting state, exact atoms | j:EntityKeyV1 | contains every economic transaction-start target, terminal parent, selected/remainder child, unchanged forensic target, and newly created result exactly once as prescribed by the kind table; EntityKeyV1 is unique regardless of role; total is not_applicable because parent/child snapshots can overlap |
      | ApplicationRealizedValueProjectionSetV1 | application | application ID | application kind, descriptor complete hash, ApplicationResultRangeSetV1 hash, currency/unit/scale | exact expected-result member plus its immutable group-final complete strict economic state value-projection object | j:EntityKeyV1 | key/state/range membership equals ApplicationResultRangeSetV1 and the application subgroup's canonical final-per-key fold exactly with one member per unique EntityKeyV1; ApplicationRangeValueProjectionV1 and this containing set/hash are forbidden members, total is not_applicable |
      | PayoutLotChildRangeSetV1 | PayoutLotV1 | transaction-start parent payout-lot ID | parent full hash/range/atoms, operator, currency/unit/scale | stable child payout-lot ID, immutable range start/end, exact atoms | u:range-start,u:range-end,b:child-ID | nonempty only for partitioned; children are nonoverlapping and exactly cover/conserve the parent once; child projections/full/event hashes are forbidden |
      | DebtRangeChildRangeSetV1 | DebtRangeV1 | transaction-start parent DebtRange ID | parent full hash/range/atoms, operator, currency/unit/scale | stable child DebtRange ID, immutable range start/end, exact atoms | u:range-start,u:range-end,b:child-ID | nonempty only for partitioned; children are nonoverlapping and exactly cover/conserve the parent once; mutable child hashes/state are forbidden |
      | DebtRecoveryApplicationChildRangeSetV1 | DebtRecoveryApplicationV1 | transaction-start parent recovery ID | parent full hash/value-projection hash, source range, actual dependent DebtRange transaction-start ID/full hash/value-projection hash/range, DebtRangeChildRangeSetV1 hash, affine offset, atoms, operator, currency/unit/scale | stable child recovery ID, source start/end, target start/end, exact atoms, aligned actual dependent DebtRange child stable ID/range | u:source-start,u:source-end,u:target-start,u:target-end,b:child-ID | nonempty only for aligned partial debt_reopen; encoded after DebtRangeChildRangeSetV1, children preserve the offset and exact dependent child identity and exactly cover/conserve both equal-length parent ranges once; mutable child/event/full-result hashes are forbidden |
      | EnforcementDispositionCoverageChildRangeSetV1 | EnforcementDispositionCoverageV1 | transaction-start parent coverage ID | parent full hash/source-lot/range/atoms, operator, currency/unit/scale | stable child coverage ID, source range start/end, exact atoms | u:range-start,u:range-end,b:child-ID | nonempty only for partitioned; children are nonoverlapping and exactly cover/conserve the parent once; mutable child hashes/state are forbidden |

  Scenario Outline: Submitted-payment resolution sets have exact registered preimages
    Given CanonicalTypedSetV1 kind "<set>" has owner kind "<owner>", owner ID copied from "<owner ID>", scope "<scope>", member fields "<members>", and total sort key "<key>"
    Then its conservation/cardinality contract is "<contract>"

    Examples:
      | set | owner | owner ID | scope | members | key | contract |
      | PendingSubmittedNegativeSetV1 | payout_instruction | TowerPayoutInstructionV1 payout-instruction ID | payout ID, operator, instruction complete hash, PayoutSendFenceV1 ID/complete hash/Core tuple, currency/unit/scale | PendingSubmittedNegative stable ID, transaction-start complete hash/value-projection hash/revision and pending state, negative entitlement ID, plan-local range, causal positive source ID/range, submitted lot ID/transaction-start complete hash/value-projection hash/range, exact atoms | b:pending-ID,u:plan-local-start,u:plan-local-end,b:submitted-lot-ID,u:submitted-range-start,u:submitted-range-end | present only with one or more pending records; members equal the complete transaction-start pending snapshot, ranges are nonoverlapping within each submitted-lot namespace, and total atoms equals pending recourse |
      | PendingFailureSegmentSetV1 | pending_failure_resolution_descriptor | deterministic failure descriptor stable ID | payout_confirmed_failed stable event ID/group index, payout instruction and authenticated rail-failure complete hashes, transaction-start submitted lot ID/complete hash/value-projection hash/full range, currency/unit/scale | PendingSubmittedNegative stable ID, transaction-start pending value-projection hash, affected intersection start/end, exact atoms | b:pending-ID,u:affected-start,u:affected-end | permits empty only for an unaffected instruction lot; otherwise positive nonoverlapping intersections equal that lot's exact intersection with PendingSubmittedNegativeSetV1 and total atoms equals affected atoms |
      | PendingFailureLotResultSetV1 | pending_failure_resolution_descriptor | deterministic failure descriptor stable ID | payout_confirmed_failed stable event ID/group index, transaction-start submitted lot ID/complete hash/value-projection hash/full range, PendingFailureSegmentSetV1 hash, currency/unit/scale | affected_cancelled or unaffected_returned role, exact pending/application authority or canonical unaffected absence, ClassificationAuthoritySetV1 hash, HoldReferenceSetV1 hash, dust-cycle authority/transition or canonical absence, stable result lot ID, immutable range start/end, exact atoms, expected resulting cancelled or mature_payable or withheld state, complete resulting PayoutLotValueProjectionV1 | u:range-start,u:range-end,b:result-lot-ID | before assigning child IDs, canonical boundaries split only on the pre-ID semantic tuple defined below and every adjacent identical tuple merges; only then are range-scoped sets, transitions, result IDs, and projections encoded, and the unique ranges exactly cover/conserve the submitted lot once; a whole uniform result retains its stable lot ID, while a mixed result uses its PayoutLotChildRangeSetV1 children and total atoms equals parent atoms |
      | PendingFailureResolutionDescriptorSetV1 | payout_confirmed_failed | payout_confirmed_failed stable event ID | payout ID, instruction complete hash, authenticated rail-failure complete hash, PendingSubmittedNegativeSetV1 hash or canonical no-pending absence, operator, currency/unit/scale | deterministic descriptor stable ID, transaction-start submitted lot stable key/complete hash/value-projection hash/state/range/atoms, resulting terminal-parent value projection plus PayoutLotChildRangeSetV1 hash or canonical whole-result absence, PendingFailureSegmentSetV1 hash, PendingFailureLotResultSetV1 hash, dust-cycle parent transition or canonical absence, affected atoms, unaffected atoms, exact journal allocation | b:lot-ID,b:parent-or-empty,u:range-start,u:range-end | required for every confirmed failure; contains exactly one descriptor for every instruction lot, uses an empty segment set and zero affected atoms when no pending range intersects, nested result totals conserve each lot, segment unions exhaust every present pending range once, and total atoms equals instruction atoms |
      | PendingSuccessResolutionDescriptorSetV1 | payout_succeeded | payout_succeeded stable event ID | payout ID, instruction complete hash, authenticated rail-success complete hash, PendingSubmittedNegativeSetV1 hash, operator, currency/unit/scale | PendingSubmittedNegative stable ID/transaction-start value-projection hash and stable key, one submitted-lot ID/transaction-start complete hash/range intersection, exact atoms, expected resolved_paid PendingSubmittedNegativeValueProjectionV1, prescribed debt_create stable event ID/group index, DebtCreateResultSetV1 complete hash | b:pending-ID,u:plan-local-start,u:plan-local-end,b:submitted-lot-ID,u:intersection-start,u:intersection-end | present iff PendingSubmittedNegativeSetV1 is present; exactly one member per pending record, membership and order equal that set, intersections and totals equal pending atoms, and every prescribed child event/result set is unique |
      | DebtCreateResultSetV1 | debt_create | debt_create stable event ID | closed DebtCreateScopeV1 fields selected by the exact origin table below | source payout-lot ID, transaction-start complete hash/value-projection hash/state/range, resulting paid PayoutLotValueProjectionV1 hash or canonical preexisting-paid tag, PendingSubmittedNegative ID/prior/result projection hashes or canonical absence, EnforcementDispositionCoverage ID/creation projection hash or canonical absence, created DebtRange stable ID/range/atoms and complete creation value projection | b:source-lot-ID,u:source-range-start,u:source-range-end,b:DebtRange-ID | exactly one result per origin-authorized source range, each source/result range and atom count is equal, IDs are unique, total atoms equals the debt_create event, and origin-foreign member fields are canonically absent |

  Scenario Outline: DebtCreateScopeV1 has one exact acyclic shape per origin
    Given DebtCreateResultSetV1 has origin "<origin>"
    Then its scope contains operator/currency/unit/scale plus exactly "<authority>"
    And every authority field belonging to another origin has canonical absence
    And economic_reversal is encoded after its descriptor but before ApplicationRealizedValueProjectionSetV1, resolved_submitted_success is encoded before PendingSuccessResolutionDescriptorSetV1, and paid_enforcement_clawback is encoded after EnforcementCoverageResultSetV1
    And no scope contains its own set hash, either later containing-set hash, or a current-group event complete hash

    Examples:
      | origin | authority |
      | economic_reversal | parent entitlement_delta stable ID/complete hash, ApplicationDescriptorSetV1 complete hash, application index/ID and descriptor complete hash, plan-local range, causal positive source-event ID/range |
      | resolved_submitted_success | parent payout_succeeded stable ID/expected group index without its current-group complete hash, authenticated rail-success complete hash, PendingSubmittedNegative stable ID/transaction-start value-projection hash, transaction-start submitted lot ID/complete hash/range, resulting paid PayoutLotValueProjectionV1 hash |
      | paid_enforcement_clawback | CompensationForfeitureDecisionV1 complete hash, EnforcementAuthorizedRangeSetV1 complete hash, EnforcementCoverageResultSetV1 complete hash |

  Scenario: Submitted-resolution nested sets form one acyclic construction graph
    Given a payout instruction and its transaction-start pending and submitted-lot snapshots are fixed
    When a final authenticated rail result is reconciled
    Then PendingSubmittedNegativeSetV1 is encoded before either final result event
    And on failure each PendingFailureSegmentSetV1 is encoded before its PendingFailureLotResultSetV1, both are encoded before their strict descriptor, and PendingFailureResolutionDescriptorSetV1 is encoded last
    And on success each prescribed DebtCreateResultSetV1 is encoded from stable child IDs and value projections before PendingSuccessResolutionDescriptorSetV1
    And a nested member may bind preexisting complete hashes and current-group stable IDs/value projections only, never its containing set hash, a current-group event complete hash, a resulting ledger/control-leaf hash, or a post-commit full-object hash
    And absent pending recourse uses canonical absence for PendingSubmittedNegativeSetV1 and success resolution, while confirmed failure still requires PendingFailureResolutionDescriptorSetV1 with one descriptor per instruction lot and empty PendingFailureSegmentSetV1 objects

  Scenario: Failure-result boundaries use a pre-ID semantic tuple without a dust or scope cycle
    Given one transaction-start submitted lot is classified after authenticated failure
    When PendingFailureLotResultSetV1 boundaries are chosen
    Then the tuple is exactly affected-or-unaffected role, PendingSubmittedNegative/application stable authority identity and revision or canonical absence, resulting state and maturity classification, every applicable classification-authority identity/revision/result/effective tuple, every applicable hold identity/revision/reason/effective tuple, and dust-cycle ID/generation/prior-projection hash/deadline/transition-role or canonical absence
    And the tuple uses transaction-start source coordinates only and explicitly excludes result lot/child IDs, result ranges, range-scoped ClassificationAuthoritySetV1 or HoldReferenceSetV1 hashes, resulting DustLotReferenceSetV1/hash, resulting dust projection, and every result projection/hash
    And boundaries are the minimal segmentation where that tuple is constant, after which deterministic child IDs/ranges are assigned and the exact range-scoped authority/hold sets, dust transition, and resulting projections are encoded
    And deriving a boundary from a result ID/hash, retaining two adjacent identical tuples, or merging different tuples rejects the resolution set

  Scenario Outline: Enforcement and debt-writeoff source/result sets have exact registered preimages
    Given CanonicalTypedSetV1 kind "<set>" has owner kind "<owner>", owner ID copied from "<owner ID>", scope "<scope>", member fields "<members>", and total sort key "<key>"
    Then its conservation/cardinality contract is "<contract>"

    Examples:
      | set | owner | owner ID | scope | members | key | contract |
      | EnforcementAuthorizedRangeSetV1 | compensation_forfeiture_decision | CompensationForfeitureDecisionV1 decision ID | decision series/revision, immutable TargetScopeDigestV1, operator, Tower, homogeneous unpaid_forfeiture or paid_clawback disposition, currency/unit/scale | SettlementReceiptV2 ID/complete hash, source PayoutLot stable ID, transaction-start complete hash/value-projection hash/revision, exact withheld or paid state, half-open range start/end, exact atoms | b:settlement-ID,b:payout-lot-ID,u:range-start,u:range-end | nonempty; ranges are unique/nonoverlapping, at most one contiguous range comes from one transaction-start lot leaf, every member state matches disposition, and total atoms equals the one nonzero signed disposition total |
      | EnforcementCoverageResultSetV1 | enforcement_consumer | forfeit or paid-enforcement debt_create stable event ID | CompensationForfeitureDecisionV1 complete hash, EnforcementAuthorizedRangeSetV1 hash, disposition, operator, currency/unit/scale | authorized source member key, EnforcementDispositionCoverage stable ID/source range/atoms/kind and complete immutable creation/current-at-consumer value projection | b:settlement-ID,b:source-lot-ID,u:source-range-start,u:source-range-end,b:coverage-ID | exactly one current coverage result per consumed authorized range in identical order, IDs/ranges are unique, each amount equals its source, and total atoms equals consumed decision atoms |
      | DebtWriteoffAuthorizedRangeSetV1 | debt_writeoff_decision | DebtWriteoffDecisionV1 decision ID | decision series/revision, immutable TargetScopeDigestV1, operator, currency/unit/scale | DebtRange stable ID, transaction-start complete hash/value-projection hash/revision and outstanding state, half-open range start/end, exact atoms | b:DebtRange-ID,u:range-start,u:range-end | nonempty unique nonoverlapping ranges with at most one contiguous range per transaction-start debt leaf; every amount is outstanding and total atoms equals signed writeoff atoms |
      | HistoricalAcceptedTermsAuthoritySetV1 | destructive_decision | CompensationForfeitureDecisionV1 or DebtWriteoffDecisionV1 decision ID | closed decision kind, decision series/revision, immutable TargetScopeDigestV1, authorized-range-set complete hash, operator, currency/unit/scale | exact authorized target-member canonical key, source GrantCompensationSnapshotV1 or originating TowerPayoutInstructionV1 ID/complete hash selected by decision kind, historical accepted_terms PayoutEligibilityFactV1 stable series/revision/complete hash/effective/expiry/fact-ledger commit tuples and accepted-terms version/complete hash payload | same canonical target-member key as the authorized range set | nonempty and one-to-one in identical order with the authorized range set; each fact is byte-identical to its immutable earning lineage for forfeiture or debt-origin instruction lineage for writeoff, and total is not_applicable |
      | DebtWriteoffResultSetV1 | debt_writeoff | debt_writeoff stable event ID | DebtWriteoffDecisionV1 complete hash, DebtWriteoffAuthorizedRangeSetV1 hash, operator, currency/unit/scale | authorized source member key, whole-source resulting written_off DebtRangeValueProjectionV1 or canonical partial absence, selected child stable ID/range/atoms, resulting terminal-parent projection, DebtRangeChildRangeSetV1 hash/count, and complete resulting child value-projection array in identical child-set order or canonical whole-result absences | b:source-DebtRange-ID,u:source-range-start,u:source-range-end,b:selected-result-DebtRange-ID | exactly one compound result per authorized source in identical order; a partial result's array includes selected written_off plus every outstanding remainder and its terminal parent, source and selected ranges/atoms are equal, all IDs are unique, selected atoms total the signed writeoff amount, and outer total atoms equals that selected total |

  Scenario: Signed enforcement and writeoff authority cannot float to a later source state
    Given a purpose signer commits EnforcementAuthorizedRangeSetV1 or DebtWriteoffAuthorizedRangeSetV1
    When the one-use compensation transaction consumes that decision
    Then every source entity ID, revision, transaction-start complete hash, value-projection hash, state, range, operator, Tower where applicable, and currency matches at the serializable transaction/group start
    And the event binds the exact authorized-set complete hash plus its exact result-set complete hash
    And a hold, payment, partition, recovery, writeoff, coverage, or other source transition committed before this transaction makes the decision stale and causes the whole transaction to fail without partial state or journal mutation
    And the only in-group source partition exception is the exact decision-bound unpaid-forfeiture PayoutLot helper: authorized parent snapshot equals helper prior, helper terminal parent and selected-child revision-1 projections derive from it, and the forfeit consumer prior equals that selected-child projection

  Scenario: Destructive target scope and historical terms have acyclic exact derivations
    Given EnforcementAuthorizedRangeSetV1 or DebtWriteoffAuthorizedRangeSetV1 has its canonical ordered transaction-start members
    Then TargetScopeDigestV1 is the fixed-length unpadded case-preserving base64url SHA-256 digest over strict UTF-8 JCS [destructive-target-scope-v1,network-ID,decision-kind,operator-ID,Tower-ID-or-canonical-absence,currency,unit,scale,ordered array of each member object type/stable ID/transaction-start complete hash/value-projection hash/revision/state/range/atoms]
    And that digest excludes decision ID/series/revision, set owner/hash, policy, finding, approval, terms, issue time, and every resulting object so decision identity and both sets are constructible without a hash cycle
    And HistoricalAcceptedTermsAuthoritySetV1 has exactly one member for every authorized range under the same target key/order and resolves its signed fact through immutable source lineage plus the greatest accepted trust publication at the fact's original commit tuple
    And each fact was current, accepted, and inside its effective/expiry interval at the source grant or originating payout-instruction authority tuple; normal later expiry or terms revision does not rewrite historical consent
    And a broken lineage, payload mismatch, missing member, fact not valid at that historical use, newly learned compromise covering the original fact commit, duplicate target, alternate digest, or current source-state change rejects the decision or its consumption

  Scenario: Every nonapplication result set equals the event-local affected-state commitment
    Given PendingFailureLotResultSetV1, PendingSuccessResolutionDescriptorSetV1, DebtCreateResultSetV1, EnforcementCoverageResultSetV1, or DebtWriteoffResultSetV1 is bound by a compensation event group
    When its relationship to the prescribed consumer event and group index is verified
    Then every resulting state EntityKeyV1 appears exactly once in that event's resulting AffectedStateProjectionSetV1 and its complete value-projection bytes are identical to the result member
    And every mutated transaction-start key appears exactly once in the corresponding prior AffectedStateProjectionSetV1 with bytes identical to the signed source member, while immutable unchanged forensic/source projections are relationship-checked against the named preexisting object or earlier group result
    And expected PendingSubmittedNegative resolved projections and prescribed DebtRange creation projections in each success descriptor equal that prescribed debt_create child's resulting set at its signed group index; payout_succeeded owns only the submitted-lot-to-paid mutations
    And failure result membership plus each outer failure descriptor's terminal-parent projection equals the payout_confirmed_failed resulting PayoutLot subset, enforcement coverage membership equals the forfeit or paid-enforcement debt_create resulting coverage subset, and every whole/parent/selected/remainder projection carried by DebtWriteoffResultSetV1 equals the debt_writeoff resulting DebtRange subset
    And for paid_clawback the EnforcementDispositionCoverage key/projection referenced by each DebtCreateResultSetV1 member is byte-identical to the same member of EnforcementCoverageResultSetV1
    And an omitted, extra, differently keyed, stale, or byte-different projection rejects the whole event group before state, posting, control, or rail-result finalization

  Scenario Outline: Tower scope and payout authority/reference sets have exact registered preimages
    Given CanonicalTypedSetV1 kind "<set>" has owner kind "<owner>", owner ID copied from "<owner ID>", scope "<scope>", member fields "<members>", and total sort key "<key>"
    Then its conservation/cardinality contract is "<contract>"

    Examples:
      | set | owner | owner ID | scope | members | key | contract |
      | TowerIDScopeSetV1 | compensation_event | non-payout compensation event stable ID | event type, operator, currency/unit/scale | Tower ID | b:Tower-ID | nonempty sorted unique membership equals every Tower derived from all event-owned affected source/result entity immutable lineages; an entitlement_delta contains exactly its causal SettlementReceiptV2 Tower because nested application targets belong to child owners, and total is not_applicable |
      | TowerIDScopeSetV1 | payout | payout ID | operator, currency/unit/scale | Tower ID | b:Tower-ID | nonempty sorted unique membership equals every Tower derived from PayoutLotAtomRangeSetV1 and is byte-identical in every preparation, payout-family event, authority leaf, and instruction for that payout; total is not_applicable |
      | PayoutLotRangeSetV1 | compensation_event | non-payout compensation event stable ID | event type, operator, currency/unit/scale | payout-lot stable ID, closed preexisting or current_group_abort_void_hold source tag, preexisting transaction-start complete hash/value-projection hash/revision/state with current-group fields canonically absent or current-group latest earlier abort/void/withhold event stable ID/group index/intermediate value-projection complete hash/revision/state with preexisting full/value-projection hashes canonically absent, parent-or-empty, range start/end, exact atoms, Tower ID, SettlementReceiptV2 ID/hash | b:payout-lot-ID,b:parent-or-empty,u:range-start,u:range-end | nonempty exact event-authorized lot snapshot with nonoverlapping active leaf ranges; current_group_abort_void_hold is permitted only for a child prescribed by AbortVoidHoldPlanSetV1, each member's earlier projection is byte-identical to the latest lower-index group result for that key—parent abort/void for the first mutation or the latest overlapping prior withhold child thereafter—and its revision/index obey the same-group projection rule, every other consumer requires preexisting, and total atoms equals the event's affected lot atoms |
      | PayoutLotAtomRangeSetV1 | payout | payout ID | payout-preparation ID, operator, currency/unit/scale | reserved payout-lot stable ID/range/atoms, transaction-start source parent ID/complete hash/value-projection hash/revision and mature_payable state, whole-source equality or deterministic partial-child ID/PayoutLotChildRangeSetV1/creation projection, Tower ID, SettlementReceiptV2 ID/hash | b:source-parent-ID,u:reserved-range-start,u:reserved-range-end,b:reserved-lot-ID | nonempty reserved ranges are unique/nonoverlapping active source leaves with at most one contiguous reserved subrange per transaction-start source leaf, their sum equals gross reserved share atoms X, and this identical set is bound from preparation through final rail result; selected available B minus X equals R and is excluded into the remainder/dust binding |
      | PayoutLotPartitionHelperSetV1 | payout_lot_consumer | intended lot_cancel, prepare_payout, or unpaid forfeit consumer stable event ID | consumer event type/expected group index, operator, currency/unit/scale, exact ApplicationResultRangeSetV1 or PayoutLotAtomRangeSetV1 or EnforcementAuthorizedRangeSetV1 authority-set kind/hash with foreign alternatives absent | partition_lot helper stable ID/expected group index and zero-based ordinal, transaction-start source parent ID/parent-or-empty/complete hash/value-projection hash/revision/state/range start/range end/atoms, PayoutLotChildRangeSetV1 hash, consumer-selected child ID/range/atoms, intended consumer stable ID/group index | b:source-parent-ID,b:parent-or-empty,u:range-start,u:range-end | one member for every and only proper-subrange source parent in canonical parent-key order, each zero-based ordinal equals its array index, no parent repeats, total atoms equals the sum of partitioned parents, and the canonical empty set with total zero is required when every selected source is whole |
      | TowerSelectedPayoutLotRangeSetV1 | tower_lifecycle_payout_authority | TowerLifecyclePayoutAuthorityV1 stable leaf ID | payout ID, operator, Tower ID, currency/unit/scale, PayoutLotAtomRangeSetV1 hash | exact complete PayoutLotAtomRangeSetV1 member fields copied without addition or omission | b:source-parent-ID,u:reserved-range-start,u:reserved-range-end,b:reserved-lot-ID | nonempty and exactly equals the PayoutLotAtomRangeSetV1 members whose immutable Tower is this owner Tower; whole/partial source-parent semantics remain identical and total atoms equals that Tower's contribution to gross reserved X |
      | TowerLifecyclePayoutAuthoritySetV1 | payout | payout ID | payout-preparation ID, operator, currency/unit/scale, TowerIDScopeSetV1 hash, PayoutLotAtomRangeSetV1 hash | complete strict TowerLifecyclePayoutAuthorityV1 leaf containing Tower ID, exact current TowerLifecycleEventV1 revision/complete hash/compensation disposition/effective Core tuple, and TowerSelectedPayoutLotRangeSetV1 hash/count/atoms | b:Tower-ID | one leaf per TowerIDScopeSetV1 member in identical Tower order, each selected subset is exhaustive, no Tower repeats, and total atoms across leaf subsets equals PayoutLotAtomRangeSetV1 |
      | CoveredPayoutAuthoritySetV1 | compensation_ledger_head | CompensationLedgerHeadV1 head ID | head sequence, SQL snapshot transaction ID hash, compensation ledger sequence, trust-document version | complete strict covered payout-authority leaf fields enumerated below | b:payout-ID,b:payout-preparation-ID | exactly every payout preparation covered by the SQL snapshot appears once; empty is permitted only when that snapshot covers no payout preparation, and total atoms is not_applicable |
      | CompensationEventIDSetV1 | payout | payout ID | payout-preparation ID/complete hash, CompensationLedgerHeadV1 complete hash, operator, currency/unit/scale | compensation-event stable ID, event type, committed complete hash, ledger sequence | u:ledger-sequence,b:event-ID | nonempty and exactly equals every source/current-state compensation event needed by PayoutLotAtomRangeSetV1 in ledger order; duplicate ID/hash or an event after the covered head is rejected, total atoms is not_applicable |
      | FundingSliceIDSetV1 | payout | payout ID | payout-preparation ID/complete hash, CompensationLedgerHeadV1 complete hash, operator, currency/unit/scale | SettlementReceiptV2 ID/complete hash and funding-allocation-array hash, complete strict slice fields copied from that receipt: slice ID, funding kind, opaque source-lot reference, source-lot/reservation/provenance identities and hashes, source credit authority sequence, consumer-cost amount, Station allocation, source and cumulative-cost intervals, exact grant-bound FundingAllocationPolicyV1 series/revision/complete hash and allocation rule, currency/unit/scale, exact contributed atoms | b:settlement-ID,b:funding-slice-ID,u:source-start,u:source-end | nonempty and exactly exhausts funding lineage of PayoutLotAtomRangeSetV1 without inventing a separate FundingSliceV1 hash or reusing an interval; total contributed atoms equals gross reserved X, while retained R lineage is excluded with the remainder/dust binding |
      | SettlementReceiptHashSetV1 | payout | payout ID | payout-preparation ID/complete hash, CompensationLedgerHeadV1 complete hash, operator, currency/unit/scale | SettlementReceiptV2 stable ID, complete hash | b:settlement-ID | nonempty sorted unique membership equals receipts reached from every selected lot and FundingSliceIDSetV1; total atoms is not_applicable |

  Scenario: Payout typed sets have one cycle-free construction and reuse order
    Given a payout selection and all transaction-start source snapshots are fixed
    When PayoutPreparationV1 is constructed
    Then TowerIDScopeSetV1 and PayoutLotAtomRangeSetV1 are encoded without a preparation/event/head/instruction complete hash, each TowerSelectedPayoutLotRangeSetV1 is encoded next, and TowerLifecyclePayoutAuthoritySetV1 is encoded after those subsets
    And the preparation binds those complete hashes before its post-commit complete hash exists
    And a later CompensationLedgerHeadV1 encodes CoveredPayoutAuthoritySetV1 from already committed strict authority leaves without its own complete hash in the set
    And only after that head commits are CompensationEventIDSetV1, FundingSliceIDSetV1, and SettlementReceiptHashSetV1 encoded for TowerPayoutInstructionV1
    And every later payout-family event and send-fence relationship reuses the exact payout-owned TowerIDScopeSetV1, PayoutLotAtomRangeSetV1, and TowerLifecyclePayoutAuthoritySetV1 hashes rather than reconstructing a differently owned alias
    And each TowerLifecyclePayoutAuthorityV1 stable leaf ID is the fixed-length unpadded case-preserving base64url SHA-256 digest over the UTF-8 bytes of the strict JCS array [TowerLifecyclePayoutAuthorityV1-leaf-id-v1,network-ID,payout-ID,Tower-ID], so its TowerSelectedPayoutLotRangeSetV1 owner ID is one unambiguous byte string

  Scenario: AuthoritativePaymentRevisionV1 has one provider-neutral strict preimage
    Given an authenticated provider fetch is committed as AuthoritativePaymentRevisionV1
    Then its strict JCS object contains only schema/network/protocol, provider-neutral adapter ID/version, merchant/account binding hash, authenticated-fetch credential version, payment source ID/kind, currency/unit/scale, Core source-revision sequence and previous revision complete hash or canonical first absence, canonical bounded provider revision string, original principal, cumulative captured principal, cumulative refunds, cumulative open-dispute amount, cumulative lost-dispute amount, cumulative released/won-dispute amount, cumulative processor fee, fee pending or final state, capture/refund/dispute/fee maturity states, immutable capture-maturity Core tuple or canonical not-yet-mature absence, ProviderPaymentEventIDSetV1 complete hash, fee-finality policy/deadline, provider-observed time claims, authenticated response digest, and Core fetch/commit authority tuple
    And all amounts are bounded canonical nonnegative integers in one currency/scale, cumulative category relationships are valid, the source revision is exactly prior plus one, and equal provider revision with different strict bytes is conflict-quarantined
    And the first revision whose authenticated capture-maturity state becomes mature sets that tuple byte-identically to its independently assigned Core fetch/commit tuple, every earlier revision requires absence, and every later revision preserves it byte-identically despite refunds/disputes/fee changes
    And provider event bodies, webhook claims, Tower input, floating values, unknown fields, and provider timestamps as Core authority are forbidden

  Scenario Outline: Payment authority and journal sets have exact registered preimages
    Given CanonicalTypedSetV1 kind "<set>" has owner kind "<owner>", owner ID copied from "<owner ID>", scope "<scope>", member fields "<members>", and total sort key "<key>"
    Then its conservation/cardinality contract is "<contract>"

    Examples:
      | set | owner | owner ID | scope | members | key | contract |
      | ProviderPaymentEventIDSetV1 | payment_source | payment source ID | provider-neutral adapter ID, merchant/account binding hash, Core source-revision sequence, canonical provider revision | bounded canonical provider event ID | b:provider-event-ID | nonempty sorted unique membership equals the authenticated fetch's complete required provider event lineage; total is not_applicable |
      | AuthoritativePaymentRevisionSetV1 | entitlement_aggregate | entitlement aggregate ID | SettlementReceiptV2 ID/complete hash/funding-allocation-array hash, operator, compensation-policy version, currency/unit/scale | provider-neutral adapter ID, merchant/account binding hash, payment source ID/kind, Core source-revision sequence, canonical provider revision, AuthoritativePaymentRevisionV1 complete hash, immutable capture-maturity Core tuple or canonical not-yet-mature absence, ProviderPaymentEventIDSetV1 complete hash | b:adapter-ID,h:merchant-binding,b:payment-source-ID,b:source-kind | exactly one current committed revision for every external-cash source reached from the receipt's funding allocation and no grant-only source; every duplicated identity/revision/maturity-tuple/event-set field is byte-identical to the strict AuthoritativePaymentRevisionV1 named by its complete hash, no source repeats, empty is forbidden for an eligible candidate, and total is not_applicable |
      | MaturitySourceRevisionSetV1 | maturity_authority | MaturityAuthorityV1 authority ID | operator, currency/unit/scale, MaturityPolicyV1 series/revision/complete hash, PayoutLotRangeSetV1 complete hash, actual maturity Core tuple | payout-lot stable ID/parent-or-empty/range/atoms, funding-slice ID, provider-neutral adapter/merchant/payment-source identity, maturity-start AuthoritativePaymentRevisionV1 sequence/complete hash/capture-maturity Core tuple, current AuthoritativePaymentRevisionV1 sequence/complete hash/ProviderPaymentEventIDSetV1 hash/capture-refund-dispute-fee states, derived required Core time and minimum global authority sequence | b:payout-lot-ID,b:parent-or-empty,u:range-start,u:range-end,b:payment-source-ID | nonempty sorted unique membership equals every selected payout-lot range exactly once, contains no grant-only source, total atoms equals PayoutLotRangeSetV1, current revision is the unique latest authenticated monotonic source revision, and each required tuple is the checked deterministic policy derivation from its immutable start tuple |
      | AbortVoidHoldPlanSetV1 | abort_or_void | abort_preparation or void_payout stable event ID | payout/preparation IDs, parent event type/expected group index, PayoutLotAtomRangeSetV1 complete hash, operator, currency/unit/scale, decision Core tuple | prescribed withhold stable event ID/expected later group index, zero-based ordinal, external_materialization or compensation_created source tag, hold kind, derived stable hold-reference ID, external authority type/ID/complete hash/series-revision-prior with canonical compensation-series absence or stable compensation hold-series ID/exact next revision/prior withhold-event ID/complete hash with canonical external-authority absence, closed hold reason, evidence/review tuple, AuthorityRangeScopeSetV1 stable ID/complete hash, source PayoutLotRangeSetV1 complete hash, and exact group-final PayoutLotValueProjectionV1 member hashes | b:hold-kind,b:stable-hold-reference-ID,h:AuthorityRangeScopeSetV1-hash | permits empty only when no new hold materialization is required; otherwise membership equals every and only newly required current external or compensation-created hold over the parent-selected ranges, ordinal equals array index, child ID is the fixed-length unpadded case-preserving base64url SHA-256 digest over UTF-8 strict JCS [AbortVoidWithholdEventV1-id-v1,network-ID,parent-event-ID,ordinal], expected index equals parent index plus one plus ordinal, each source member uses the latest lower-index intermediate projection for its exact key so overlapping children form one continuous revision chain, and no current-group event/full-object/ledger/control hash is present |
      | JournalPostingSetV1 | compensation_event | compensation event stable ID | event type, closed journal-template version, closed disposition ID, operator, TowerIDScopeSetV1 hash, currency/unit/scale | zero-based template slot, closed posting role, closed account code, debit or credit side, exact share atoms, source EntityKeyV1 or canonical absence, destination EntityKeyV1 or canonical absence, authority stable ID | u:template-slot | member count/roles/accounts/sides equal the exact disposition template with no offsetting extras, slots are contiguous from zero, debit atoms equal credit atoms, and total is not_applicable; only dispositions explicitly declared canonical-zero permit count zero with one empty array |
      | AuthorityRangeScopeSetV1 | authority_evaluation | authority-range-scope stable ID | authority consumer stable ID/expected group index, zero-based scope ordinal, operator, payout ID or canonical absence, decision Core tuple, currency/unit/scale | payout-lot stable ID, parent-or-empty, immutable range start/end, exact atoms, Tower ID, SettlementReceiptV2 ID/complete hash | b:payout-lot-ID,b:parent-or-empty,u:range-start,u:range-end | nonempty unique nonoverlapping ranges equal the exact classification/hold applicability scope; total atoms equals scope atoms and membership cannot expand after the decision tuple |
      | FeeFinalityAffectedAggregateSetV1 | fee_finality_incident | FeeFinalityIncidentV1 incident ID | provider-neutral adapter/merchant/payment-source identity hashes, last AuthoritativePaymentRevisionV1 complete hash, FeeFinalityPolicyV1 complete hash, deadline tuple, currency/unit/scale | entitlement-aggregate ID, transaction-start EntitlementAggregateValueProjectionV1 complete hash/revision/state, SettlementReceiptV2 complete hash, operator ID, AuthoritativePaymentRevisionSetV1 complete hash | b:aggregate-ID | nonempty sorted unique membership equals every current aggregate whose revision set contains that exact fee-pending source; no undefined full aggregate-object hash, unrelated aggregate, or omitted aggregate is permitted and total is not_applicable |
      | PayoutEligibilityEvidenceSetV1 | payout_eligibility_decision | payout-eligibility decision-series ID | decision revision, deterministic eligibility-scope ID, operator, payout-identity version/destination fingerprint or canonical held absence, operator-account stable series/revision/hash or canonical held absence, accepted-terms revision/hash or canonical held absence, sanctions-ruleset version/hash or canonical held absence, jurisdiction or canonical held absence, currency/unit/scale, payout rail, payout-eligibility-policy series/revision/complete hash and PayoutEligibilityEvidenceRegistryV1 complete hash, applicability-authority evidence ordinal/kind/source tag/object type/ID/complete hash or missing-self absence/Core tuple | zero-based evidence-kind ordinal, closed evidence kind, present or missing tag, exact PayoutEligibilityFactV1 kind/stable-scope/series/revision/complete hash for ordinals zero through five or exact published PayoutEligibilityPolicyV1 series/revision/complete hash for ordinal six or canonical missing absence where permitted, closed result/reason, effective Core tuple or canonical missing absence, and expiry Core tuple or canonical missing absence | u:evidence-kind-ordinal | exactly seven members in the closed kind order below; eligible requires every member present, passing, applicable, current, fresh, and unexpired, held requires the signed reason to equal the first failing kind, and policy applicability is always present; total is not_applicable |

  Scenario: JournalPostingSetV1 has one amount and state relationship
    Given a compensation event binds JournalPostingSetV1 complete hash
    When its journal relationship is verified
    Then every nonzero posting amount and source/destination key is derived from the event's exact signed delta, application, range, rail, enforcement, debt, or payout authority and, except for the prescribed success-group bridge below, agrees with its own event-local prior/resulting AffectedStateProjectionSetV1
    And payout_succeeded with pending recourse is the sole cross-event bridge: its pending-source key and DebtRange destination key are byte-identical to the prescribed PendingSuccessResolutionDescriptorSetV1 and DebtCreateResultSetV1 child result at the signed later group index, the group-final control projection includes both child mutations, and neither key is falsely inserted into payout_succeeded's event-local affected-state sets
    And every debt_receivable posting selects the group-final whole or selected non-partition-parent DebtRange EntityKeyV1 from the applicable ApplicationRealizedValueProjectionSetV1, DebtCreateResultSetV1, or DebtWriteoffResultSetV1: debt_offset selects recovered, debt_reopen and debt_create select outstanding, and debt_writeoff selects written_off, never a partial operation's terminal transaction-start parent or unselected remainder
    And unpaid forfeit selects the helper-created forfeited PayoutLot child as its liability key and newly created current EnforcementDispositionCoverage key as its destination, while a whole source is permitted only with the canonical empty helper set
    And paid-enforcement debt creation selects its newly created current coverage key, while coverage derecognition selects the group-final whole or selected derecognized coverage key from ApplicationRealizedValueProjectionSetV1 and never the terminal partition parent or a current remainder
    And the closed template table in compensation_state_machines.feature determines the only permitted posting roles, accounts, sides, count, and zero disposition for that event variant
    And entitlement_delta, resolved_submitted_success debt_create children, and every other explicitly zero-posting authority event use the one event-owner-and-scope-specific canonical empty JournalPostingSetV1 object/hash
    And an alternate order, extra balanced pair, omitted leg, duplicate slot, zero-valued member, wrong account/side/key, or debit-credit mismatch rejects the event before state or control commit

  Scenario: AuthorityRangeScopeSetV1 has a deterministic owner without a set cycle
    Given one authority consumer and its pre-ID canonical result-range boundaries are fixed
    When scope ordinal K is assigned in ascending first-member EntityKeyV1 order
    Then authority-range-scope stable ID is the fixed-length unpadded case-preserving base64url SHA-256 digest over the UTF-8 bytes of strict JCS array [AuthorityRangeScopeSetV1-owner-v1,network-ID,authority-consumer-stable-ID,expected-group-index,K]
    And the ID is computed before scope members and contains no scope-set, classification-set, hold-set, result-object, event-complete, or dust-result hash
    And ClassificationAuthoritySetV1 and HoldReferenceSetV1 for that exact range scope bind the same stable scope ID and AuthorityRangeScopeSetV1 complete hash

  Scenario: Payout eligibility evidence kinds and order are closed
    Given PayoutEligibilityEvidenceSetV1 is encoded
    Then its ordinal-to-kind mapping is exactly 0 payout_identity, 1 operator_account, 2 accepted_terms, 3 sanctions_screening, 4 jurisdiction_determination, 5 destination_verification, and 6 payout_eligibility_policy_applicability
    And every kind occurs once at its fixed ordinal even when evidence is missing, with missing using the one canonical absence shape rather than omission or null
    And the deterministic eligibility-scope ID is the fixed-length unpadded case-preserving base64url SHA-256 digest over the UTF-8 strict JCS array [PayoutEligibilityScopeV1-id-v1,network-ID,operator-ID,currency,unit,scale,payout-rail]
    And every registry-defined revision-payload field duplicated by PayoutEligibilityDecisionV1 is byte-identical to that outer field, including each canonical absence, while a registry field not duplicated outside the member remains fact-only and is authenticated through that fact's complete hash
    And each present member is byte-identical in stable scope, revision payload, object type, ID, revision, complete hash, result, effective tuple, and expiry tuple to the purpose-signed object it names
    And payout_identity, operator_account, accepted_terms, jurisdiction_determination, or destination_verification missing requires the corresponding outer identity/destination, account, terms, jurisdiction, or destination field to use its one canonical held-absence shape; the eligibility-policy series/revision/hash and exact applicability-authority source shape remain present because they authorize the held decision itself
    And an eligible outer decision permits no absence, while a held outer reason equals the first nonpassing member and no later missing member can change that deterministic reason
    And an eligible decision's outer expiry is no later than every finite member expiry and the governing payout-eligibility-policy expiry, while a held decision cannot extend any finite authority it claims remains passing
    And an extra kind, changed ordinal, omitted failing fact, present fact or policy committed/published after the decision Core commit tuple, a member not equal to its exact current stable-slot head at the decision snapshot, or result inconsistent with the purpose-signed evidence rejects the decision
    And an outer expiry after the earliest finite evidence or policy expiry rejects the decision before maturity, preparation, head creation, instruction, or send

  Scenario: Payout eligibility applicability source is selected without implementation choice
    Given the complete ordered PayoutEligibilityEvidenceSetV1 and decision result are fixed
    When PayoutEligibilityDecisionV1 binds its applicability-authority source
    Then a present member contributes its exact effective Core tuple and a missing member contributes the decision's independently assigned Core commit tuple without inventing a member effective or expiry field
    And eligible has all seven members as its prerequisite set, while held finds the fixed-ordinal first nonpassing member K and has exactly ordinals zero through K plus policy ordinal six as its prerequisite set; later fact members remain an exhaustive current snapshot but cannot change the first-failure reason or cutoff
    And the selected applicability source is the prerequisite member with the lexicographically greatest [Core time,global authority sequence,evidence ordinal] tuple: fact_or_policy copies a present member's ordinal/kind/object type/ID/complete hash/effective tuple, while missing_decision_commit copies a missing member's ordinal/kind, requires object type/ID/hash absence, and copies the decision Core commit tuple
    And the outer applicability tuple is no earlier than every authority in that exact prerequisite set, is no later than the decision Core commit tuple, and is the only cutoff compared with preparation or send-fence authority
    And any other member, max-by-signer-time, missing-object presence, present-object absence, raw untyped evidence, altered tuple, or object not byte-identical to that evidence member rejects the decision

  Scenario: PayoutEligibilityEvidenceRegistryV1 has one exact policy-bound preimage
    Given PayoutEligibilityPolicyV1 binds PayoutEligibilityEvidenceRegistryV1 complete hash and fixed member count 7
    Then the registry is one strict JCS object containing only schema/network/protocol, positive registry version, fixed member count 7, and an ordered complete entries array
    And each entry contains only zero-based ordinal, closed evidence kind, exact source object type, exact signer purpose or published_policy_self tag, closed passing-result set, closed present-failing-result set, missing permitted boolean, exact stable-series-scope field-token list, exact revision-payload field-token list, authority-anchor kind, finite-expiry-required boolean, positive bounded maximum fact-validity interval or canonical policy-not-applicable value, and positive bounded maximum fact-age-at-use interval or canonical policy-not-applicable value
    And its entries are exactly:
      | ordinal | kind | source type / purpose | passing result | failing results | stable series scope | revision payload | validity / age | anchor |
      | 0 | payout_identity | PayoutEligibilityFactV1 / payout_identity_verification_signer | verified | failed or revoked | operator ID | payout-identity verification version | positive bounded identity validity / age | independently assigned fact-ledger Core commit tuple |
      | 1 | operator_account | PayoutEligibilityFactV1 / operator_account_status_signer | active | suspended or closed | operator ID | operator-account stable series/revision/complete hash | positive bounded account validity / age | independently assigned fact-ledger Core commit tuple |
      | 2 | accepted_terms | PayoutEligibilityFactV1 / payout_terms_acceptance_signer | accepted | withdrawn or expired | operator ID | accepted-terms version/complete hash | positive bounded terms validity / age | independently assigned fact-ledger Core commit tuple |
      | 3 | sanctions_screening | PayoutEligibilityFactV1 / sanctions_screening_signer | clear | review or hit | operator ID | payout-identity version, jurisdiction, and sanctions-ruleset version/complete hash | positive bounded sanctions validity / age | independently assigned fact-ledger Core commit tuple |
      | 4 | jurisdiction_determination | PayoutEligibilityFactV1 / payout_jurisdiction_signer | supported | unsupported or unknown | operator ID and currency/unit/scale and payout rail | jurisdiction | positive bounded jurisdiction validity / age | independently assigned fact-ledger Core commit tuple |
      | 5 | destination_verification | PayoutEligibilityFactV1 / payout_destination_verification_signer | verified | failed or revoked | operator ID and currency/unit/scale and payout rail | payout-identity version and immutable destination fingerprint | positive bounded destination validity / age | independently assigned fact-ledger Core commit tuple |
      | 6 | payout_eligibility_policy_applicability | PayoutEligibilityPolicyV1 / published_policy_self | applicable | no other result is valid | decision eligibility-scope ID | exact policy series/revision/complete hash | policy-not-applicable / policy-not-applicable | first accepted CompensationPolicyDirectorySetV1 publication plus policy effective/expiry tuples |
    And missing permitted is true exactly for ordinals zero through five and false for ordinal six; all six fact entries require finite expiry and both positive interval ceilings, the policy entry uses its exact finite policy expiry, and every result/scope/payload/anchor/interval field not named by its row is forbidden
    And every stable-scope and revision-payload list contains only canonical registry field tokens, never an actual operator, policy series/revision/complete hash, evidence object, decision, containing-policy hash, or registry hash, so the registry is immutable and its containing policy has no hash cycle
    And the registry has no signer of its own: its exact complete hash gains authority only through the purpose-signed and independently published PayoutEligibilityPolicyV1 that contains it
    And an unknown/reordered/duplicate entry, changed source type/purpose/result/scope/anchor, count mismatch, opaque implementation registry, or registry hash not matching the selected policy rejects every decision that names it

  Scenario: Payout eligibility member and outer reason encodings are canonical
    Given one PayoutEligibilityEvidenceRegistryV1 entry and its evidence member presence/result are fixed
    Then a present passing member has the exact reason code not_applicable
    And a present failing member has the exact ASCII reason code formed by its registry kind token, one colon byte, and its exact failing-result token
    And a missing member is permitted only for ordinals zero through five, means no current head exists for that exact registry-derived stable slot at the decision's serializable ledger snapshot, has canonical result missing, canonical object-reference/effective/expiry absence, and exact reason code formed by its kind token plus colon plus missing
    And ordinal six policy applicability is always present with result applicable and reason not_applicable
    And an eligible decision has exact outer reason eligible; a held decision copies byte-for-byte the member reason of the fixed-ordinal first nonpassing member
    And case folding, whitespace, alternate separator, free text, numeric code, passing reason on failure, result on missing other than missing, missing policy, or outer/member disagreement rejects the decision

  Scenario Outline: PayoutEligibilityFactV1 has one closed kind-specific signed shape
    Given a payout eligibility fact has kind "<kind>"
    Then its purpose is "<purpose>", its stable-series scope is exactly "<stable scope>", and its mutable revision payload is exactly "<revision payload>"
    And its strict common signing bytes contain only schema/network/protocol, kind, purpose-specific signer key ID, deterministically derived stable fact-series ID, positive revision, previous PayoutEligibilityFactV1 complete hash or canonical first-revision absence, the row's exact stable-scope fields, the row's exact revision-payload fields with every foreign kind field canonically absent, closed result, evidence complete hash, effective Core tuple, finite expiry Core tuple, issue tuple, and independently assigned fact-ledger Core commit authority tuple
    When every universal mutation is independently applied to a common field, kind-specific field, result, evidence relationship, authority tuple, signature, or foreign-field presence
    Then strict decoding, registry mapping, purpose-signature verification, current-head CAS, or authority-anchor verification fails before an eligibility decision is accepted

    Examples:
      | kind | purpose | stable scope | revision payload |
      | payout_identity | payout_identity_verification_signer | operator ID | payout-identity verification version |
      | operator_account | operator_account_status_signer | operator ID | operator-account stable series ID/revision/complete hash |
      | accepted_terms | payout_terms_acceptance_signer | operator ID | accepted-terms version/complete hash |
      | sanctions_screening | sanctions_screening_signer | operator ID | payout-identity version, jurisdiction, and sanctions-ruleset version/complete hash |
      | jurisdiction_determination | payout_jurisdiction_signer | operator ID and currency/unit/scale and payout rail | jurisdiction |
      | destination_verification | payout_destination_verification_signer | operator ID and currency/unit/scale and payout rail | payout-identity version and immutable destination fingerprint |

  Scenario: Payout eligibility fact heads and authority anchors fail closed
    Given one registry kind and exact immutable stable-scope slot has current revision R and complete hash H
    When a fact is created, advanced, or selected for PayoutEligibilityDecisionV1
    Then stable series ID is the fixed-length unpadded case-preserving base64url SHA-256 digest over UTF-8 strict JCS [PayoutEligibilityFactV1-series-v1,network-ID,kind,exact-registry-stable-scope-JCS]
    And creation is revision 1/prior absence, every successor is exactly R plus one with immediate prior H under one current-head CAS, and exact replay is idempotent
    And every change to a row's revision payload, result, evidence, source-input version, or ruleset advances that same stable series rather than creating another series; activation of a changed input must advance every affected slot to its new assessment or a failing result before any new positive authority may use it
    And result belongs to the registry row, every duplicated outer/evidence field is byte-identical, effective is no earlier than its Core commit tuple, decision tuple is no earlier than effective and strictly before expiry, and signer issue time or opaque evidence time grants no authority
    And expiry is no later than the minimum of fact-ledger commit time plus the registry maximum fact-validity interval, purpose-signer key not-after, and every named source authority expiry that exists, while decision/use time minus fact-ledger commit time is no greater than the registry maximum fact-age-at-use interval
    And the signer key/purpose is the exact registry mapping and is valid under derived accepted trust publication at the fact-ledger Core commit tuple with later compromise cutoff overlaid
    And a gap/overflow/fork, stale fact, wrong kind/purpose/scope/result, signer-selected backdate, missing finite expiry, policy-as-fact substitution, or arbitrary signed object rejects the decision before a hold, preparation, or send fence

  Scenario: Payout eligibility decision and fact heads have one immutable scope and currentness fence
    Given eligibility scope E contains exact operator, currency, unit, scale, and payout rail and decision series D is current at revision R and complete hash H
    When a decision is created or result eligible is used to release a hold, classify or mature a lot, return a failed payout range to payable, prepare a payout, construct or accept its covered ledger head or instruction, or commit its send fence
    Then E equals the deterministic PayoutEligibilityScopeV1 ID and D equals the fixed-length unpadded case-preserving base64url SHA-256 digest over UTF-8 strict JCS [PayoutEligibilityDecisionV1-series-v1,network-ID,E]
    And one serializable transaction or read fence compare-and-swaps D/R/H, the exact six registry-derived fact stable-slot heads named by PayoutEligibilityEvidenceSetV1, the selected policy series/revision/hash/publication head, the registry hash, and every referenced purpose key's active nonrevoked state in the greatest accepted current trust publication
    And each fact head is byte-identical to the evidence member, is fresh/unexpired at that use tuple, and every duplicated mutable payload field equals the decision; an eligible decision permits no absent slot
    And any fact, input, ruleset, policy, registry, key state, decision head, identity, destination, or scope change conflicts with that positive use and fails closed, while an already current held decision remains restrictive until an explicit valid successor becomes eligible
    And creation starts only at D revision 1 with prior absence, a successor is exactly R plus one with prior H, exact replay is idempotent, and no alternate revision-1 series can exist for E

  Scenario: PayoutLot partition helpers and their consumer have one closed atomic-group shape
    Given lot_cancel, prepare_payout, or unpaid forfeit selects proper subranges from P transaction-start PayoutLot parents
    When the serializable consumer group is encoded
    Then PayoutLotPartitionHelperSetV1 contains exactly P members, one helper per distinct proper-subrange parent and none for a whole source, sorted by its registered parent key
    And the P partition_lot helpers occupy one consecutive canonical block in that order immediately before the sole authority-consuming lot_cancel, prepare_payout, or forfeit event
    And each helper signs the same PayoutLotPartitionHelperSetV1 complete hash and its member ordinal, exact consumer kind/stable ID/expected group index, exact descriptor/preparation/decision range authority, transaction-start parent snapshot, PayoutLotChildRangeSetV1, and adjustment, payout, or unpaid_forfeiture purpose without a current-group event hash
    And the helper alone changes its parent to terminal partitioned, creates every child at revision 1 in the parent's prior live state, and owns only the exact atom-conserving same-liability partition journal; it cannot cancel, reserve, forfeit, consume the descriptor/decision, or own the consumer's economic journal
    And the consumer signs that same helper-set hash, consumes the authority exactly once, takes each selected child's revision-1 value projection as its prior state, advances only selected children to revision 2, and owns the cancellation, reservation, or forfeiture posting
    And each unchanged remainder remains at revision 1, while helper prior/result and consumer prior/result AffectedStateProjectionSetV1 objects form a continuous group-index chain and the group-final state equals every bound application or enforcement result set
    And the canonical empty helper set is required for an all-whole consumer; an orphan, missing, extra, duplicate, reordered, nonadjacent, wrong-purpose, wrong-authority, wrong-consumer, or journal-owning helper rejects the entire atomic group

  Scenario: Expected and realized application sets have one acyclic equality relationship
    Given one immutable descriptor binds ApplicationResultRangeSetV1 and its ApplicationRangeValueProjectionV1 binds that hash plus ApplicationRealizedValueProjectionSetV1
    When the one-use application subgroup commits
    Then expected and realized sets have identical ordered result-role/state-kind/EntityKeyV1/prior/result-state/atom members
    And for a whole target or a range-state partition internal to one owner event, every realized projection equals that owner's resulting AffectedStateProjectionSetV1 economic value for the key
    And for a proper-subrange PayoutLot application, the subgroup is exactly its one partition_lot helper followed by its owner event; folding their signed prior/resulting AffectedStateProjectionSetV1 objects in group-index order yields one final projection per key, and ApplicationRealizedValueProjectionSetV1 equals that group-final economic key set
    And continuity requires the helper's selected-child revision-1 projection to equal the owner prior projection, while the helper's terminal parent and unchanged remainder projections and the owner's selected-child revision-2 projection form the final fold
    And ApplicationRangeValueProjectionV1 is a separate owner-event affected-state member
    And result members contain stable keys and current-group value projections only, never current-group event/full-object/ledger hashes, the containing ApplicationRange projection, or either application-result set object/hash

  Scenario: Immutable child-range sets cannot encode a gratuitous or malformed partition
    Given PayoutLotChildRangeSetV1, DebtRangeChildRangeSetV1, DebtRecoveryApplicationChildRangeSetV1, or EnforcementDispositionCoverageChildRangeSetV1 is present
    Then it has at least two positive proper range-ordered child members
    And every non-recovery child atom count equals its end minus start, the parent atom count equals its full-range end minus start, and the children exactly cover that parent once
    And every recovery child atom count equals both its positive source-range length and positive target-range length, every child preserves the parent's affine offset, and the children exactly cover both parent ranges once
    And child stable IDs are unique within the set and globally identify one immutable type-specific range-state entity, so one ID cannot name two ranges or two parents
    And a single-contiguous-selection application, preparation, adjustment, forfeiture, debt offset, debt reopen, coverage derecognition, or writeoff has exactly one selected child plus one or two remainders and therefore exactly two or three members
    And payout_confirmed_failed may instead have more than three children when its exact pre-ID semantic tuple defined above differs; it preserves every such boundary, merges every adjacent identical tuple, and only then derives each result child ID and projection
    And a one-member full-range child, zero-length child, nonmaximal split, gap, overlap, amount/range mismatch, repeated ID, child outside the parent, or child count inconsistent with the authorizing boundaries rejects the partition

  Scenario: Application result roles and segment indices are a closed language
    Given an ApplicationResultRangeSetV1 or ApplicationRealizedValueProjectionSetV1 member has a result role
    Then the role is exactly one of updated_whole_target, terminal_partition_parent, selected_child, remainder_child, created_payout_lot, created_recovery_application, created_pending_negative, created_debt_range, unchanged_target, dependent_updated_whole_target, dependent_terminal_partition_parent, dependent_selected_child, dependent_remainder_child, or unchanged_forensic_lot
    And role segment index is zero for every non-remainder role
    And remainder_child and dependent_remainder_child indices independently start at zero and increase contiguously in ascending immutable range order
    And one set contains at most one member for an EntityKeyV1 even if another role or segment index is substituted
    And an unknown role, a wrong role for the application kind, a gap or duplicate in either remainder index sequence, or a second role for one EntityKeyV1 rejects the containing signed object

  Scenario Outline: Application kind and whole-or-partial shape fix the exact result-role pattern
    Given application kind "<application>" has transaction-start shape "<shape>"
    Then its ApplicationResultRangeSetV1 contains exactly "<members>"
    And no other economic result member or role is permitted

    Examples:
      | application | shape | members |
      | lot_create | no transaction-start target | one created_payout_lot from absent to immature for the application source range |
      | debt_offset | whole target DebtRange | one updated_whole_target DebtRange from outstanding to recovered and one created_recovery_application from absent to active |
      | debt_offset | proper subrange of target DebtRange | one terminal_partition_parent DebtRange from outstanding to partitioned, one selected_child from absent to recovered, one or two range-ordered remainder_child members from absent to outstanding, and one created_recovery_application from absent to active |
      | debt_reopen | whole recovery and affine-mapped whole dependent DebtRange | one updated_whole_target DebtRecoveryApplication from active to reversed and one dependent_updated_whole_target DebtRange from recovered to outstanding |
      | debt_reopen | proper subrange of recovery and affine-mapped dependent DebtRange | one terminal_partition_parent recovery from active to partitioned, one selected_child recovery from absent to reversed, one or two remainder_child recoveries from absent to active, one dependent_terminal_partition_parent DebtRange from recovered to partitioned, one dependent_selected_child DebtRange from absent to outstanding, and one or two dependent_remainder_child DebtRanges from absent to recovered with identical affine-aligned segment boundaries |
      | lot_cancel | whole target PayoutLot | one updated_whole_target PayoutLot from its exact immature, mature_payable, or withheld prior state to cancelled |
      | lot_cancel | proper subrange of target PayoutLot | one terminal_partition_parent PayoutLot from its exact live prior state to partitioned, one selected_child from absent to cancelled, and one or two range-ordered remainder_child members from absent to that same live prior state |
      | submitted_negative_fence | submitted range, which is never partitioned here | one unchanged_target PayoutLot from reserved_submitted to reserved_submitted and one created_pending_negative from absent to pending |
      | debt_create | uncovered paid range | one unchanged_target PayoutLot from paid to paid and one created_debt_range from absent to outstanding |
      | enforcement_coverage_derecognize | whole target EnforcementDispositionCoverage | one updated_whole_target coverage from current to derecognized and one unchanged_forensic_lot PayoutLot retaining its exact forfeited or paid state |
      | enforcement_coverage_derecognize | proper subrange of target EnforcementDispositionCoverage | one terminal_partition_parent coverage from current to partitioned, one selected_child from absent to derecognized, one or two range-ordered remainder_child members from absent to current, and one unchanged_forensic_lot PayoutLot retaining its exact forfeited or paid state |

  Scenario: Application result sets are hashable in one direction without a cycle
    Given application ID, kind, parent entitlement and plan-local context, target transaction-start snapshots, deterministic child IDs/ranges, and expected states are fixed
    When the entitlement plan is encoded
    Then ApplicationResultRangeSetV1 is encoded first without an ApplicationDescriptorSetV1, descriptor, realized-set, current-group event, or full-object hash in its scope or members
    And its complete hash is placed in the descriptor before ApplicationDescriptorSetV1 is encoded
    And only the later ApplicationRealizedValueProjectionSetV1 may bind the descriptor complete hash together with the earlier ApplicationResultRangeSetV1 complete hash
